apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-container
          image: rhannachi1991/users-net-k8s:1.0.0
          env:
            - name: AUTH_API_URL
              value: 'localhost'
          ports:
            - containerPort: 8080
              name: users-port
          livenessProbe:
            httpGet:
              port: users-port
              path: /healthcheck
          readinessProbe:
            httpGet:
              port: users-port
              path: /healthcheck
        - name: auth-container
          image: rhannachi1991/auth-net-k8s:latest
          ports:
            - containerPort: 80
              name: auth-port
          livenessProbe:
            httpGet:
              port: auth-port
              path: /healthcheck
          readinessProbe:
            httpGet:
              port: auth-port
              path: /healthcheck
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: LoadBalancer
  selector:
    app: users-pod
  ports:
    - port: 8080
      targetPort: users-port
      protocol: TCP
