FROM node:current-alpine3.22
WORKDIR /app

# "Par défaut, `npm` est préfixé au début de chaque commande qu'on exécute dans le conteneur"
# Désormais, chaque commande lancée dans le conteneur sera interprétée comme une commande npm.
ENTRYPOINT ["npm"]
