FROM node:current-alpine3.22
ENV NODE_ENV=production

WORKDIR /app
COPY package*.json .
RUN npm install --production

COPY . .
# VOLUME /app/node_modules
VOLUME /app/logs

EXPOSE 80

CMD ["npm", "run", "start"]
