apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  # ReadWriteOnce : signifie que le volume peut être monté en lecture/écriture par un seul nœud à la fois
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  # on utilisant hostPath, le stockage physique reste sur le worker node.
  hostPath:
    path: /data
    type: DirectoryOrCreate
