apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-pod
  template:
    metadata:
      labels:
        app: story-pod
    spec:
      # volumes : liste des volumes que l’on souhaite mettre à disposition des conteneurs de ce Pod
      volumes:
        - name: story-volume
          # créer automatiquement le répertoire sur le worker node
          hostPath:
            path: /data # chemin sur le nœud hôte
            type: DirectoryOrCreate # crée le dossier s'il n'existe pas
      containers:
        - name: story-container
          image: rhannachi1991/k8s-story:latest
          ports:
            - containerPort: 3000
              name: web-port
          volumeMounts:
            - mountPath: /app/story # chemin à l'intérieur du conteneur où le volume sera monté
              name: story-volume    # nom du volume déclaré dans la section "volumes"

          # LivenessProbe
          livenessProbe:
            httpGet:
              port: web-port
              path: /healthcheck
          # ReadinessProbe
          readinessProbe:
            httpGet:
              port: web-port
              path: /healthcheck
---
apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story-pod
  ports:
    - port: 80
      protocol: TCP
      targetPort: web-port
  type: LoadBalancer
