version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ] # commande exécutée
#      interval: 10s      # fréquence du check (défaut: 30s)
#      timeout: 5s        # délai d’attente pour la commande (défaut: 30s)
#      retries: 3         # nombre de tentatives avant marquer “unhealthy” (défaut: 3)
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://admin:OV1sKe5HY2MogSpY@cluster0.0tnlpgh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      AUTH_API_ADDRESSS: 'http://auth:3000'
#    depends_on:
#      auth:
#        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
